case_description: "मुद्दाको विवरण"
registration_number: "दर्ता नँ"
registration_date: "दर्ता मिती"
event_date: "रुजु मिती"
case_type: "मुद्दाको किसिम"
case: "मुद्दा"
clause_holder: "फाँटवाला"
clause: "फाँट"
case_status: "मुद्दाको स्थिती"
plaintiffs: "वादीहरु"
defendants: "प्रतिवादीहरु"
plaintiff_attorneys: "वादी अधिवक्ता(हरु)"
defendant_attorneys: "प्रतिवादी अधिवक्ता(हरु)"

attachment_cases_details: "लगाब मुद्दाहरुको विवरण"
current_status: "हालको स्थिती"
date_details: "तारेख विवरण"
description: "विवरण"
date_types: "तारेखको किसिम"

date_hearing: "तारेख मिती"

case_status_details: "मुद्दाको स्थितीको बिस्तृत विवरण"
date: "मिती"
situation: "स्थिती"

hearing_details: "पेशी को विवरण"
heading_date: "सुनवाइ मिती"
judges: "न्यायाधीशहरू"
judgments: "आदेश /फैसलाको किसिम"